---
  - name: Configure munge
    shell: create-munge-key < /dev/null creates=/etc/munge/munge.key
    when: not munge_key.stat.exists
    notify: restart munge

  - name: Start munge service
    service: name=munge state=started
