---
  - name: Create munge key
    shell: create-munge-key < /dev/null creates=/etc/munge/munge.key
    when: not munge_key.stat.exists and munge_key_password == ''
    notify: restart munge
  
  - name: Create munge key with password
    shell: echo -n "{{ munge_key_password }}" | sha512sum | cut -d' ' -f1 >/etc/munge/munge.key
    when: not munge_key.stat.exists and munge_key_password != ''

  - name: Start munge service
    service: name=munge state=started
