---
  - name: Start Munge service
    service: name=munge state=started
    register: munge_installed
    ignore_errors: yes

  - name: Include "{{ansible_os_family}}" munge recipe if package is not present
    include: "{{ansible_os_family}}.yaml"
    when: munge_installed|failed

  - name: Register munge key
    stat: path=/etc/munge/munge.key
    register: munge_key

  - name: set munge log directory access rights
    file: path=/var/log/munge state=directory mode=0700

  - name: set log directory access rights
    file: path=/var/log state=directory mode=0755

  - name: Include "{{ssh_type_of_node}}" munge recipe
    include: "{{ssh_type_of_node}}.yaml"
