---
  - name: Check munge key
    local_action: wait_for path=/etc/munge/munge.key timeout=600
    when: not munge_key.stat.exists

  - name: If there is not munge key copy one
    include: sudo_copy.yaml src=/etc/munge/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode="0400"
    when: not munge_key.stat.exists
    notify: restart munge

  - name: Make sure the munge service is started
    service: name=munge state=started
