---

  - block:
    - name: Wait for munge key
      local_action: wait_for path=/etc/munge/munge.key timeout=600

    - name: Copy munge key from fe
      include: sudo_copy.yaml src=/etc/munge/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode="0400"

    when: not munge_key.stat.exists and munge_key_password == ''
