---
- name: Converge
  hosts: all
  become: true

  tasks:

    - name: "Include grycap.munge"
      include_role:
        name: "ansible-role-munge"

    - name: Test munge is in path
      shell: munge -n | unmunge
      changed_when: False

    - name: Test munge key exists 
      file:
        path: /etc/munge/munge.key
      changed_when: False